version: '2'
services:
  configserver:
    image: application/config-server:cs

  eurekaserver:
    image: application/eureka-server:es

  zuulgateway:
    image: application/zuul-gateway:zg
    ports:
      - "8080:5555"
    environment:
      SERVER_PORT: "5555"
      EUREKASERVER_PORT:   "8761"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "application_db"

  licensing-service:
    image: application/licensing-service:ls
    #ports: entry point only via gateway
    #  - "8080:8080" #network-port:container-port
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"

  licensing-service2:
    image: application/licensing-service:ls
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"

  organization-service:
    image: application/organization-service:os
    #ports:
    #  - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      IS_MISBEHAVE: "false"

  organization-service2:
    image: application/organization-service:os
    #ports:
    #  - "8086:8086"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8086"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      IS_MISBEHAVE: "true"
