version: '2'
services:
  configserver:
    image: application/config-server:cs
    ports:
      - "8888:8888"

  eurekaserver:
    image: application/eureka-server:es
    ports:
      - "8761:8761"

  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "application_db"

  licensing-service:
    image: application/licensing-service:ls
    ports:
      - "8080:8080" #network-port:container-port
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"

  organization-service:
    image: application/organization-service:os
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"

  organization-service2:
    image: application/organization-service:os
    ports:
      - "8086:8086"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8086"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
