spring:
  application:
    name: licensingservice
  cloud:
    stream:
      bindings:
        inboundOrganizationChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup #makes sure that only one instance will consume message
      kafka:
        binder:
          zkNodes: kafkaserver
          brokers: kafkaserver

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true