application:
  misbehavingInstance: false #used to simulate misbehaving service to test hystrix
spring:
  application:
    name: organizationservice
  cloud:
    stream:
      bindings:
        outboundOrganizationChanges:
          destination:  orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: kafkaserver
          brokers: kafkaserver
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true

